#!/bin/bash

echo "╔════════════════════════════════════════╗"
echo "║  GITHUB SECRETS SETUP                  ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "📝 Required Secrets:"
echo ""
echo "1. GEMINI_API_KEY"
echo "   Your Google Gemini API key"
echo ""
echo "2. OPENAI_API_KEY"
echo "   Your OpenAI API key (optional)"
echo ""
echo "3. DATABASE_URL"
echo "   Database connection string"
echo "   Example: 'file:./hotel.db'"
echo ""
echo "════════════════════════════════════════"
echo "📝 How to Add:"
echo ""
echo "1. Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret"
echo "4. Save"
echo ""
echo "✅ Done!"
